<?php

namespace App\Services;

use Illuminate\Support\Facades\DB;

class BackupService
{
    private array $tables = [
        'classes',
        'students',
        'face_descriptors',
        'attendance_records',
        'leave_requests',
        'holidays',
        'parent_student_links',
        'student_user_links',
        'user_roles',
        'app_settings',
    ];

    public function jsonPayload(string $email): array
    {
        $dump = [];
        $total = 0;

        foreach ($this->tables as $table) {
            $rows = DB::table($table)->limit(100000)->get()->map(fn ($row) => (array) $row)->all();
            $dump[$table] = ['rows' => $rows, 'count' => count($rows)];
            $total += count($rows);
        }

        return [
            'meta' => [
                'version' => '1.0',
                'format' => 'laravel-presensi-fulldump',
                'generated_at' => now()->toISOString(),
                'generated_by' => $email,
                'table_count' => count($this->tables),
                'total_rows' => $total,
            ],
            'tables' => $dump,
        ];
    }

    public function sqlDump(string $email): string
    {
        $parts = [
            '-- Sistem Presensi - Full Database Dump (SQL)',
            '-- Generated: '.now()->toISOString(),
            '-- Generated by: '.$email,
            '',
        ];

        foreach ($this->tables as $table) {
            $rows = DB::table($table)->limit(100000)->get()->map(fn ($row) => (array) $row)->all();
            $parts[] = "-- Data: {$table} (".count($rows).' rows)';
            foreach ($rows as $row) {
                $columns = collect(array_keys($row))->map(fn ($column) => "`{$column}`")->implode(', ');
                $values = collect($row)->map(fn ($value) => $this->sqlValue($value))->implode(', ');
                $parts[] = "INSERT INTO `{$table}` ({$columns}) VALUES ({$values});";
            }
            $parts[] = '';
        }

        return implode("\n", $parts);
    }

    private function sqlValue(mixed $value): string
    {
        if ($value === null) {
            return 'NULL';
        }
        if (is_bool($value)) {
            return $value ? '1' : '0';
        }

        return "'".str_replace("'", "''", (string) $value)."'";
    }
}
